version: '3'

services:
  customenu_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "Hakj5KPs"
      POSTGRES_USER: customenu_user
      POSTGRES_DB: customenu_db
    ports:
      - "5432:5432"
