version: '3.3'

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: customenu-portainer
    ports:
      - '9000:9000'
      - '8000:8000'
    networks:
      - customenu-network
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './db-data:/data'

# todo: add api
# todo: add admin
# todo: add app